config/routes.rb
Rails.application.routes.draw do
  get 'accounts/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users
  resources :messages
  resources :accounts
  resources :pay_orders
  resources :rates
  resources :transaction_types

  #get "posts/new" => 'posts#new_post', :as => :post

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  mount ActionCable.server, at: '/cable'

  get '/users/conversations/:id' => 'conversations#show'

  resources :conversations do
    resources :messages
  end

 get '/auth/:provider/callback', to: 'sessions#create'


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @connected_users = ConnectedUser.all
    if user_signed_in?
      @aux_user = nil

      @connected_users.each_with_index do |connected_user, index|
           if connected_user.user.id ==
                  current_user.id
              @aux_user= connected_user
             return
           end
      end

      if @aux_user == nil
       connected_user=ConnectedUser.new
       connected_user.user=current_user
       connected_user.user.connected=true
       #TODO check if this is needed
       connected_user.user.save
       connected_user.save
       #TODO improve this soo we dont need to hit database
       @connected_users = ConnectedUser.all
      end

    end

  end

  def use_conditions

  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_blue_div.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 blue">
      <a class="area" href="#">
        <div class="block">
          <div class="img-holder">
            <div class="buy-bitcoins"></div>
          </div>
          <h2>Envio de Remesas </h2>

          <p> Venemarket.com es un sitio donden de manera sencilla cualquier persona puede enviar remesas desde Panama
            y Colombia a Venezuela.
            Depositando o por medio transferencias bancarias. Lo que nos hace diferentes es que sabesmos el valor
            de contar con el dinero a tiempo.

          </p>
        </div>
      </a>
    </div>
    <div class="col-lg-6 blue">
      <a class="area" href="#">
        <div class="block">
          <div class="img-holder">
            <div class="trade-icon"></div>
          </div>
          <h2>Ordenes de pago</h2>

          <p>Nuesto algoritmo para procesar ordenes de pago y una gran liquidez, permiten
            manejar un alto Volumen de ordenes, y gran escalabilidad en el mercado.
            Gracias a estandares de seguridad
            altos su informacion permenece segura con nostros</p>

        </div>
      </a>
    </div>
  </div>
</div>

app/views/static_pages/_info.html.erb
<div class="row">
  <h2 class="info-why">Por que Escojer Venemarket.com? </h2>

  <div class="info-holder" id="why">
    <ul>
      <li>
        <div class="icon">
          <span class="glyphicon glyphicon-ok-sign"></span>
        </div>
        <span>Opciones de pago</span>
        <h2>
          Bancos mas populares: Banesco Panamá, Bancolombia, Citi Bank, Mercatil.
        </h2>
      </li>

      <li>
        <div class="icon">
          <span class="glyphicon glyphicon-dashboard"></span>
        </div>
        <span>Gran Liquidez</span>
        <h2>
          Contamos con una amplia liquidez en los bancos antes mencionados, lo que nos permite ser eficientes en los
          págos
        </h2>
      </li>

      <li>
        <div class="icon">
          <span class="glyphicon glyphicon-thumbs-up"></span>
        </div>
        <span> Pagos inmediatos</span>
        <h2>
          Grantizamos pagos en menos de 24 horas
        </h2>
      </li>

    </ul>
  </div>
</div>

app/views/static_pages/_rate_section.html.erb
<section class="platform">
  <div class="platform-statistic">
    <div class="container">
      <ul>
        <li>
          <a href="#">
            <h2>Precio del EUR</h2>
            <span> <%= current_rate.value %> VES </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</section>

app/views/static_pages/_social.html.erb
<div class="blue_ligth">
  <!-- Work Row -->
  <div class="container">
    <div class="row">
      <div class="col-lg-6 blue">
        <a class="area" href="#">
          <div class="img-holder">
            <div class="buy-bitcoins"></div>
          </div>
          <h2> Inicia session con Google </h2>
          <%= link_to user_google_oauth2_omniauth_authorize_path,
                      class: "btn btn-block btn-social btn-google" do %>
              <span class="fa fa-google"></span> Iniciar session con Google
          <% end %>

        </a>
      </div>
      <div class="col-lg-6 blue">
        <a class="area" href="#">
          <div class="img-holder">
            <div class="trade-icon"></div>
          </div>
          <h2>Inicia session con Facebook</h2>
          <%= link_to user_facebook_omniauth_authorize_path,
                      class: "btn btn-block btn-social btn-facebook" do %>
              <span class="fa fa-facebook"></span> Iniciar session con Facebook

          <% end %>
        </a>
      </div>
    </div>
  </div>

</div>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
    <% if current_user.admin? %>
        <li><%= render :template => 'connected_users/index' %></li>
    <% end %>

        <%= render 'shared/send_money' %>

        <%= render 'shared/recipient_account' %>

        <div class="row">
          <div class="col-sm-3">
            <a href="#">
              <div class="box">
                <h3>Mis datos</h3>
                <i class="fa fa-user"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-3">

            <%= link_to pay_orders_path do %>

                <div class="box">
                <h3>Solicitudes</h3>
                <i class="fa fa-inbox"></i>
              </div>

            <% end %>

          </div>
          <div class="col-sm-3">

            <%= link_to accounts_path do %>

                <div class="box">
                <h3>Cuentas</h3>
                <i class="fa fa-money"></i>
              </div>

            <% end %>

          </div>
          <div class="col-sm-3">
            <a href="#">
              <div class="box">

                <h3>Notificacion</h3>
                <i class="fa fa-envelope"></i>
              </div>
            </a>
          </div>
        </div>

<% else %>
    <%= render 'social' %>
    <%= render 'rate_section' %>
    <div class="blue_gradient">
      <!-- Work Row -->
      <%= render 'blue_div' %>
      <%= render 'info' %>
    </div>
    <%= render 'layouts/footer' %>
<% end %>
<%= render 'layouts/chat_buttom' %>
<script>

    function getParameters() {
        //Params obj
        var params = {};
        var string = document.URL.toString();

        //To lowercase
        //To array
        url = string.split('?');

        url = url[1];

        //Iterate over url parameters array
        var length = url.length;
        for (var i = 0; i < length; i++) {
            //Create prop
            var prop = url[i].slice(0, url[i].search('='));
            //Create Val
            var value = url[i].slice(url[i].search('=')).replace('=', '');
            //Params New Attr
            params[prop] = value;
        }
        return value;
    }
    ;

    var ready = function () {


                var param = getParameters();
                if (param == 1
                        ) {
                    $("#chat").click();
                }
            }

            ;


    $(document).ready(ready);
    $(document).on("page:load", ready);


    function start_suport_conversation(sid, rip) {
//        var sender_id = $(this).data('sid');
//        var recipient_id = $(this).data('rip');
        var sender_id = sid;
        var recipient_id = rip;

        $.post("/conversations", { sender_id: sender_id, recipient_id: recipient_id }, function (data) {
            chatBox.chatWith(data.conversation_id);
        });
    }
    ;

</script>