config/routes.rb
Rails.application.routes.draw do
  get 'accounts/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users
  resources :messages
  resources :accounts
  resources :pay_orders
  resources :rates
  resources :transaction_types

  #get "posts/new" => 'posts#new_post', :as => :post

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  mount ActionCable.server, at: '/cable'

  get '/users/conversations/:id' => 'conversations#show'

  resources :conversations do
    resources :messages
  end

 get '/auth/:provider/callback', to: 'sessions#create'


end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    #TODO ver si esta duplicada la consulta????
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  layout false

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: {conversation_id: @conversation.id}
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  #other user
  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.username %> </h1>
  </div>
  <div class="chatboxoptions">
    <!--
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    -->
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <input class="chatboxtextarea" type="text" data-cid="<%= @conversation.id %>" data-cuid="<%= @current_user.id %>"
         data-remote="true"/>
</div>

<%#=subscribe_to conversation_path(@conversation)  %>

<script>
    function open_window(kindofcall) {

        if (kindofcall == 'video') {
            var windowOpen = window.open("/video_chat/show", "test", "height=600,width=800");
        }
        if (kindofcall == 'audio') {
            var windowOpen = window.open("/video_chat/audio_call", "test", "height=600,width=800");
        }


    }

</script>