config/routes.rb
Rails.application.routes.draw do
  get 'accounts/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users
  resources :messages
  resources :accounts
  resources :pay_orders
  resources :rates
  resources :transaction_types

  #get "posts/new" => 'posts#new_post', :as => :post

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  mount ActionCable.server, at: '/cable'

  get '/users/conversations/:id' => 'conversations#show'

  resources :conversations do
    resources :messages
  end

 get '/auth/:provider/callback', to: 'sessions#create'


end

app/models/pay_order.rb
class PayOrder < ApplicationRecord

  mount_uploader :capture_in, CaptureInUploader

  belongs_to :account
  belongs_to :rate
  belongs_to :transaction_type
  belongs_to :user
  accepts_nested_attributes_for :account

  attr_accessor :current_step

  validates :amount_out, presence: true, numericality: { only_float: true}
  validates :amount_in, presence: true, numericality: {only_float: true}
  validates :account_id, presence: true
  validates :transaction_type_id, presence: true
  validates :user_id, presence: true
  validates :capture_in, presence: true
  validate  :picture_size

 #validates the size of an upload image
  def picture_size
    if capture_in.size > 5.megabytes
      errors.add(:capture_in,"debe ser menor a 5MB.")
    end
  end

  def current_step?(step_key)
    #should return false
    current_step.blank? || current_step == step_key
  end


end

app/controllers/pay_orders_controller.rb
class PayOrdersController < Wicked::WizardController

  steps :show_rate,:last_step, :confirm_data

  before_action :sing_in_user
  before_action :save_previous_url

  def new
    if current_user.accounts.all.length == 0
      flash[:warning] = 'Debes agregar primero una bancaria cuenta de Venezuela'
      redirect_to controller: 'accounts', action: 'new'
    else
      @pay_order = PayOrder.new
      @account = Account.new
    end
  end

  def create
    @pay_order = PayOrder.new(pay_oder_params)
    @pay_order.rate = current_rate
    @pay_order.user = current_user
    @pay_order.transaction_type = TransactionType.find_by(status: "Pendiente por Pagar")
    if @pay_order.save
      flash[:danger] = @pay_order.capture_in.current_path
      flash[:success] = 'Orden de pago ha sido creada exitosamente'
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def index
    @pay_orders = current_user.pay_orders.paginate(page: params[:page])
  end

  def show
    @pay_order = PayOrder.find_by_id(params[:id])
  end

  def update
    if step == :show_rate
      params[:pay_order][:account_id] = '1'
      @pay_order = PayOrder.find_by_id()
      @pay_order.rate = current_rate
      @pay_order.user = current_user
      @pay_order.transaction_type = TransactionType.find_by(status: "Pendiente por Pagar")
    end
    params[:pay_order][:current_step] = step
    @pay_order.update_attributes(pay_oder_params)
    render_wizard @pay_order
    #end
  end

  def save_previous_url
    session[:my_previous_url] = URI(request.referer || '').path
  end


  def pay_oder_params

    params.require(:pay_order).permit(:amount_in, :amount_out, :account_id, :capture_in, :capture_in_cache,
                                      :current_step)
  end



end

app/helpers/pay_orders_helper.rb
module PayOrdersHelper
end

app/views/pay_orders/_pay_order.html.erb
</thead>
<tbody>
<tr>
  <th scope="row"> <%= link_to pay_order.id, pay_order_path(pay_order.id) %></th>

  <td>
    <%= pay_order.created_at.to_date %>
  </td>

  <td>
    <%= pay_order.user.username %>
    <%#= link_to pay_order.user.username, 'user_path( pay_order.user.id )' %>
  </td>

  <td>
    <%= pay_order.account.holdername.truncate(15) + " (" + pay_order.account.bank.bankname.truncate(10) + ")" %>

  </td>
  <td>
    <% if pay_order.transaction_type.status == 'Pendiente por Pagar' %>
        <i class="fa fa-cog">
          <%= pay_order.transaction_type.status %>
        </i>

    <% end %>
    <% if pay_order.transaction_type.status == 'Marcado como Pagado' %>

        <i class="fa fa-check-circle">
          <%= pay_order.transaction_type.status %>
        </i>
    <% end %>
    <% if pay_order.transaction_type.status == 'Cancelado' %>

        <i class="status-good fa fa-ban">
          <%= pay_order.transaction_type.status %>
        </i>

    <% end %>
  </td>

  <td>
    <%= pay_order.amount_out %>
  </td>

  <td>
    <%= pay_order.amount_in %>
  </td>

</tr>

</tbody>

app/views/pay_orders/index.html.erb
<%= render 'shared/send_money' %>

<%= will_paginate %>
<table class="table">
  <thead class="thead-light">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Creado en</th>
    <th scope="col">Comprador  </th>
    <th scope="col">Beneficiario - (Banco)</th>
    <th scope="col">Estado de la transacción</th>
    <th scope="col">Bolivares</th>
    <th scope="col">Euros</th>
  </tr>

  <%= render @pay_orders %>
</table>

<%= will_paginate %>

app/views/pay_orders/last_step.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-6">
      <h1> Instrucciones</h1>

      <div class="row">
      Selecciona una de tus cuentas bancarias previamente registradas,
      en caso de no aparesca niguna cuenta en la lista desplegable, debes presionar
      el botón amarillo "agregar cuenta"
      </div>

      <div class="row">

        <%= link_to new_account_path, remote: true, data: {target: '#uploadpost', toggle: 'modal'}, class: "btn btn-warning" do %>
            <i class="fa fa-plus">
              <i class="fa fa-university"> Nueva cuenta bancaria </i>
            </i>

        <% end %>

      </div>
    </div>

    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-4">total en Euros:</div>

        <div class="col-sm-8">value</div>
      </div>

      <div class="row">
        <div class="col-sm-4"> total en Bolivares:</div>

        <div class="col-sm-8"> value</div>
      </div>
    </div>

    <%= form_for @pay_order, html: {multipart: true} do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="col-sm-6 col-sm-offset-3">

          <%= f.label 'Cuenta destino' %>
          <br>

          <%= f.collection_select(:account_id, current_user.accounts.all, :id,
                                  :name_with_bank, required: true) %>

        </div>

    <% end %>

    <table class="table">
      <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Creado en</th>
        <th scope="col">Beneficiario - (Banco)</th>
        <th scope="col">Estado de la transacción</th>
        <th scope="col">Bolivares</th>
        <th scope="col">Euros</th>
      </tr>

      <%#= render @pay_orders %>
    </table>

  </div>
</div>

<div id="modal-window" class="modal hide" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/pay_orders/new.html.erb
<div class="container">
  <div class="row">


  <%= form_for @pay_order, html: {multipart: true} do |f| %>

        <%= render 'shared/error_messages', object: f.object %>
        <div class="row col-sm-3 ">

          <%= f.label 'Tasa' %>
          <%= f.text_field :aux, value: current_rate.value, readonly: true, id: "ligth-gray", disabled: true %>

          <%= f.label 'Monto en Euros' %>
        <%= f.text_field :amount_in, required: true, pattern: "[0-9]{1,3}",
                         type: "numeric" %>

        <%= f.label 'monto en bolivares' %>
        <%= f.text_field :amount_out, readonly: true, class: "bolivares" %>
      </div>
        <div class="row col-sm-6 ">

          <div class="col-sm-12 col-sm-offset-1">
            <%= f.label 'Adjuntar comprobante de pago' %>
            </br>
            <%= image_tag @pay_order.capture_in, id: "img_prev" %>
            <%= f.file_field :capture_in, onchange: "readURL(this);", required: true, accept: 'image/jpeg,image/png' %>
            </br>
            <%= f.hidden_field :capture_in_cache %>
          </div>
        </div>

        <div class="col-sm-10 col-sm-offset-2">
          <%= f.label 'Cuenta destino' %>
        </div>

        <div class="col-sm-8 ">

          <div class="row">
            Selecciona una de tus cuentas bancarias previamente registradas,
            en caso de no aparescan en la lista desplegable, debes presionar
            el botón amarillo "agregar cuenta"
          </div>
          <br>

          <div class="col-sm-6 col-sm-offset-3">
            <%= link_to new_account_path, remote: true, data: {target: '#uploadpost', toggle: 'modal'}, class: "btn btn-warning" do %>
                <i class="fa fa-plus">
                  <i class="fa fa-university"> Nueva cuenta bancaria </i>
                </i>

            <% end %>
          </div>
        </div>

        <div class="col-sm-6 col-sm-offset-1">
          </br>

          <%= f.collection_select(:account_id, current_user.accounts.all, :id,
                                  :name_with_bank, {include_blank: 'Selecciona una cuenta'}, {required: true}) %>

          </br>
          </br>

      </div>


        <div class="col-sm-6 col-sm-offset-1">

          <%= f.submit "Enviar", class: "btn btn-primary" %>
        </div>
  <% end %>
  </div>
</div>
<div id="modal-window" class="modal hide" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $("#pay_order_amount_in").keyup(function () {
        var css_klass, inpt;
        css_klass = $(this).attr("class");
        aux = $(this).attr('value', $(this).val());
        inpt = $(this).val();
        $("#pay_order_amount_out").val(inpt *<%= current_rate.value %>);
    });

    $(document).ready(function () {
        $("input[type=numeric]").keypress(function (event) {
            if ((event.which < 32) || (event.which > 126)) return true;
            return jQuery.isNumeric($(this).val() + String.fromCharCode(event.which));
        });// numeric.keypress;
    });// document.ready;


    function readURL(input) {

        var size_in_magebytes = input.files[0].size / 1024 / 1024;
        if (size_in_magebytes > 5) {

            alert("El temaños del archivo debe ser inferior a 5M");
            return 0;
        }

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#img_prev')
                        .attr('src', e.target.result)
                        .width(250)
                        .height(150);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#img_prev").click(function () {

       document.getElementById("pay_order_capture_in").click();

    });
</script>

app/views/pay_orders/show.html.erb
<div class="row">

  <div class="row col-sm-6">

    <%= @pay_order.user.username %>

  </div>

  <div class="row col-sm-6">

    <%= @pay_order.user.email %>

  </div>

  <div class="row col-sm-6">
    <%= image_tag @pay_order.capture_in.url, class:'user_pay_capture' if @pay_order.capture_in? %>
  </div>


  <div class="row col-sm-6">
    Descargar imagen

  </div>


  <div class="row col-sm-6">
    monto a transferir bolivares:
    <%= @pay_order.amount_out %>

  </div>
  <div class="row col-sm-6">
    EUROS:
    <%= @pay_order.amount_in %>
  </div>


</div>

app/views/pay_orders/show_rate.html.erb
<div class="container">
  <div class="row">

    <%= form_for @pay_order, url: wizard_path, method: :put, html: {multipart: true} do |f| %>
        <h1 id="form_title">Registra tu Orden de pago</h1>

        <%= render 'shared/error_messages', object: f.object %>
        <div class="col-sm-2 col-sm-offset-5">

          <%= f.label 'Tasa' %>
          <%= f.text_field :aux, value: current_rate.value, disabled: true, id: "ligth-gray" %>
        </div>

        <div class="col-sm-6 col-sm-offset-3">

          <%= f.label 'Monto en Euros' %>
          <%= f.text_field :amount_in, required: true, patter: "[0-9]{1,3}" %>
        </div>

        <div class="col-sm-6 col-sm-offset-3">

          <%= f.label 'monto en bolivares' %>
          <%= f.text_field :amount_out, readonly: true, class: "bolivares" %>
        </div>


        <div class="col-sm-6 col-sm-offset-3 center">
          <%= f.label 'Adjunta el Comprobante de pago' %>
          </br>
          <%= image_tag @pay_order.capture_in, id: "img_prev" %>
          <%= f.file_field :capture_in, onchange: "readURL(this);" %>
          </br>

        </div>
        <div class="row">


          <div class="col-sm-6">

            <%= link_to root_path, class: 'btn btn-default' do %>
                <i class="fa fa-arrow-left"> Atras</i>
            <% end %>

          </div>

          <div class="col-sm-6">
            <%= f.submit 'Siguiente', class: 'btn btn-success pull-right fa fa-arrow-right' %>

          </div>

        </div>
  <% end %>
  </div>


</div>


<script type="text/javascript" charset="utf-8">
    $("#pay_order_amount_in").keyup(function () {
        var css_klass, inpt;
        css_klass = $(this).attr("class");
        aux = $(this).attr('value', $(this).val());
        inpt = $(this).val();
        $("#pay_order_amount_out").val(inpt *<%= current_rate.value %>);
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#img_prev')
                        .attr('src', e.target.result)
                        .width(200)
                        .height(200);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

</script>