config/routes.rb
Rails.application.routes.draw do
  get 'accounts/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users
  resources :messages
  resources :accounts
  resources :pay_orders
  resources :rates
  resources :transaction_types

  #get "posts/new" => 'posts#new_post', :as => :post

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  mount ActionCable.server, at: '/cable'

  get '/users/conversations/:id' => 'conversations#show'

  resources :conversations do
    resources :messages
  end

 get '/auth/:provider/callback', to: 'sessions#create'


end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :bank
  belongs_to :user

  has_many :pay_orders

  validates :holdername, presence: true

  validates :number, presence: true, length: {is: 20}

  validates :documentid, presence: true

  validates :bank_id, presence: true

  validates :user_id, presence: true

  def name_with_bank
    "#{bank.bankname} - #{holdername} - #{number}"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord

  has_many :accounts

  validates :bankname, presence: true,
            length: {maximum: 100}

end

app/models/connected_user.rb
class ConnectedUser < ApplicationRecord
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    #TODO ver si esta duplicada la consulta????
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates :content, presence: true
  scope :for_display, -> { order(:created_at).last(20) }

  def mentions
    content.scan(/@(#{User::NAME_REGEX})/).flatten.map do |username|
      User.find_by(username: username)
    end.compact
  end

end

app/models/pay_order.rb
class PayOrder < ApplicationRecord

  mount_uploader :capture_in, CaptureInUploader

  belongs_to :account
  belongs_to :rate
  belongs_to :transaction_type
  belongs_to :user
  accepts_nested_attributes_for :account

  attr_accessor :current_step

  validates :amount_out, presence: true, numericality: { only_float: true}
  validates :amount_in, presence: true, numericality: {only_float: true}
  validates :account_id, presence: true
  validates :transaction_type_id, presence: true
  validates :user_id, presence: true
  validates :capture_in, presence: true
  validate  :picture_size

 #validates the size of an upload image
  def picture_size
    if capture_in.size > 5.megabytes
      errors.add(:capture_in,"debe ser menor a 5MB.")
    end
  end

  def current_step?(step_key)
    #should return false
    current_step.blank? || current_step == step_key
  end


end

app/models/rate.rb
class Rate < ApplicationRecord

  has_many :pay_orders
  validates :value, presence: true, numericality: {only_float: true}

end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord

  has_many :pay_orders

  validates :status,presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  has_many :messages
  has_many :pay_orders
  has_many :accounts

  validates :username, presence: true,
            length: {maximum: 50}
=begin

  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
=end
  #devise  concerns validates the rest
  validates :email, length: {maximum:100 }

  def self.from_omniauth(auth)

    logger.debug "name" + " " + auth.info.name
    logger.debug "prov" + " " +  auth.provider
    logger.debug "uid" + " " +  auth.uid
    logger.debug "email" +  " " + auth.info.email
    #TODO in DB first_or_create  if no user found then create one
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
      user.email = auth.info.email
      user.username = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
    #TODO catch the BD exception and show it to the user

  end

end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

  #before_action :current_user_admin
  before_action :sing_in_user

  def new
    if current_user_admin?
      @rate = Rate.new
    else
      flash[:danger] = 'Solo el usuario administrado puede acceder '
      redirect_to root_path
    end

  end

  def create
    @rate = Rate.new(rate_params)
    if @rate.save
      flash.now[:success] = 'Orden de pago ha sido creada exitosamente'
      redirect_to root_path
    else
      flash.now[:danger] = 'ha habido un error'
      render 'new'
    end
  end

  def rate_params
    params.require(:rate).permit(:value)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

  # Returns HTML from input text using GitHub-flavored Markdown.
  def markdown_to_html(text)
    Kramdown::Document.new(text, input: 'GFM').to_html
  end

  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end

end

app/helpers/pay_orders_helper.rb
module PayOrdersHelper
end

app/helpers/rates_helper.rb
module RatesHelper

  def current_rate
    Rate.last
  end

  def current_rate_ves_eur
    ves_eur = 1/current_rate.value
    ves_eur.round(6)
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
=begin
  # Logs in the given user.
  def log_in(user)
    cookies.signed[:user_id] = user.id
    if (ConnectedUser.find_by(user_id: user.id)== nil)
      connected_user=ConnectedUser.new
      connected_user.user=user
      connected_user.user.connected=true
      connected_user.user.save
      connected_user.save
    end

  end

  def log_out
    connected_user = ConnectedUser.find_by(user_id: current_user.id)
    if (connected_user != nil)
      connected_user.user.connected=false
      connected_user.user.save
      connected_user.destroy
    end

    cookies.delete(:user_id)
    @current_user = nil

  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
=end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def get_admin
    User.find_by(admin: true)
  end

  def current_user_admin?
    if current_user.admin == true
      return true
    else
      return false
    end
  end



end

app/views/shared/_connected_users.html.erb
<% if @connected_users %>
    <ul>
      <% @connected_users.each_with_index do |connected_user, index| %>

          <% unless connected_user.user.id ==
                  current_user.id %>
              <li>
                <div class="inner-div-chat" id="chat-name"><%= connected_user.user.username %></div>
                <div class="inner-div-chat" id="chat-btn">
                  <button class="btn btn-success btn-xs" onclick="start_conversation(<%=current_user.id %>, <%= connected_user.user.id %>)">Send
                    Msg
                  </button>
                </div>
                <!--<div class="inner-div-chat" id="chat-status" ><%= connected_user.user.connected %></div>-->
              </li>
          <% end %>
      <% end %>
    </ul>
<% end %>


<script>

    function start_conversation(sid, rip) {
//        var sender_id = $(this).data('sid');
//        var recipient_id = $(this).data('rip');

        var sender_id = sid;
        var recipient_id = rip;

        $.post("/conversations", { sender_id: sender_id, recipient_id: recipient_id }, function (data) {
            chatBox.chatWith(data.conversation_id);
        });
    }
    ;

</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= t('The form contains') %>
        <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">
    Añade la cuenta del Beneficiario en Venezuela
  </h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">

  <%= form_for(@account) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="col-sm-6 col-sm-offset-3">

        <%= f.label 'Cuenta destino ' %>
        <br>
        <%= f.collection_select(:bank_id, Bank.all, :id, :bankname,
                                {include_blank: 'Selecciona un banco'}, required: true) %>
      </div>

      <div class="col-sm-6 col-sm-offset-3">

        <%= f.label 'Nombre del Beneficiario en Venezuela' %>
        <%= f.text_field :holdername, required: true, placeholder: "titular de la cuenta",
                         pattern: "[a-zA-Z]{3,}[a-zA-Z\s]*",
                         oninvalid: "this.setCustomValidity('Introduce al menos 3 letras')",
                         oninput: "this.setCustomValidity('')" %>
      </div>

      <div class="col-sm-6 col-sm-offset-3">
        <%= f.label 'Numero de cuenta del beneficiario' %>
        <%= f.text_field :number, required: true, placeholder: "numero de cuenta", type: "numeric",
                         pattern: "[0-9]{20}", oninvalid: "this.setCustomValidity('Introduce los 20 numeros de cuenta')",
                         oninput: "this.setCustomValidity('')" %>
      </div>

      <div class="col-sm-6 col-sm-offset-3">

        <%= f.label 'documento' %>
        <%= f.text_field :documentid, required: true, placeholder: "V18123456 o J410532427",
                         type: "text", pattern: "([v,r,e]|[V,R,E])[0-9]{6,8}",
                         oninvalid: "this.setCustomValidity('Ejemplo: V18208301, E80123456 o J410532427')",
                         oninput: "this.setCustomValidity('')" %>
      </div>
      <div class="col-sm-6 col-sm-offset-3">

        <%= f.submit "Enviar", class: "btn btn-primary" %>
      </div>

  <% end %>
</div>
<div class="modal-footer">
</div>
<script>
    $(document).ready(function () {
        $("input[type=numeric]").keypress(function (event) {
            if ((event.which < 32) || (event.which > 126)) return true;
            return jQuery.isNumeric($(this).val() + String.fromCharCode(event.which));
        });// numeric.keypress;
    });// document.ready;
</script>

app/views/shared/_navbar_left.html.erb
<ul class="navbar-nav mt-2 mt-lg-0">

  <li class="nav-item">
    <%= link_to "Home", root_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "Tasa del dia", rates_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "Servicios", root_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "Promociones", root_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "FAQS", root_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Contactanos", root_path, class: "nav-link" %>
  </li>
</ul>

app/views/shared/_navbar_rigth.html.erb
<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
  <% if user_signed_in? %>
      <li class="nav-item">
        <a href="#" class="nav-link">Hola, <%= current_user.username %></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user"></i>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">
            <i class="fa fa-user"> <%= current_user.username %> </i>
          </a>
          <%= link_to new_user_registration_path, class: "dropdown-item" do %>
              <i class="fa fa-edit"> Editar perfil </i>
          <% end %>

          <%= link_to new_user_registration_path, class: "dropdown-item" do %>
              <i class="fa fa-tachometer"> Panel de control </i>
          <% end %>
          <div class="dropdown-divider"></div>

          <%= link_to destroy_user_session_path, class: "dropdown-item", method: :delete do %>
              <i class="fa fa-sign-out fa-fw"> Cerrar sesión</i>
          <% end %>

        </div>
      </li>
  <% else %>
      <li class="nav-item"><%= link_to new_user_registration_path, class: "nav-link padding-side-15" do %>
            <i class="fa fa-check-square-o"> Registro</i>
        <% end %>
      </li>

      <li class="nav-item"><%= link_to new_user_session_path, class: "nav-link padding-side-15" do %>
            <i class="fa fa-user"> iniciar sesión</i>
        <% end %>
      </li>
  <% end %>
</ul>

app/views/shared/_recipient_account.html.erb
<div class="send_panel">
  <h4> realiza la transferencia a la cuenta que te indique el admisitrador</h4>

  <div class="row">

    <div class="col-sm-9 border-light">
      contacta con nuestros administradores medianta el chat, ellos te indicaran la cuenta
      a la cual realizar el pago, es importante seguir todos los pasos que ellos te indiquen
    </div>
    <%= render 'layouts/chat_buttom' %>

  </div>


</div>

app/views/shared/_send_money.html.erb
<div class="send_panel">
  <h3>Realizar un envío de remesa</h3>

  <div class="row">

    <div class="col-sm-9 border-light">
      Presione el botón "enviar remesa" y se mostrará un formulario que le ayudará paso a paso en su
      operación.
    </div>

    <div class="col-sm-3">
      <%= link_to new_pay_order_path, class: "btn btn-primary" do %>
    <i class="fa fa-eur"> Enviar remesa </i>
      <% end %>
    </div>

  </div>

</div>

app/views/shared/_side_bar.html.erb
<div class="sidebar col-sm-3 bg-white">

  <div class="menu">
    <h3>Menu</h3>
  </div>

  <ul class="navbar-nav">
    <%= active_link_to root_path, class: "navbar-link", active: :exact do %>
        <li class="nav-item pt-2 pb-2">
        <i class="fa fa-home"> Home</i>
        </li>

    <% end %>

    <%= active_link_to new_pay_order_path, class: "navbar-link", active: :exact do %>
        <li class="nav-item pt-2 pb-2">
          <i class="fa fa-eur"> Enviar remesa </i>
        </li>

    <% end %>

    <%= active_link_to new_account_path, class: "navbar-link", active: :exact do %>
        <li class="nav-item pt-2 pb-2">
          <i class="fa fa-university"> Añadir cuenta bancaria </i>
        </li>

    <% end %>

    <%= active_link_to pay_orders_path, class: "navbar-link", active: :exact do %>
        <li class="nav-item pt-2 pb-2">
          <i class="fa fa-eur"> Transacciones </i>
        </li>

    <% end %>

    <%= link_to root_path, class: "navbar-link" do %>
        <li class="nav-item pt-2 pb-2">
          <i class="fa fa-user"> <%= current_user.username %> </i>
        </li>
    <% end %>

  </ul>
</div>